#!/usr/bin/env bash

NATIVE_IMAGE=$(command -v native-image)

if [ -z "$NATIVE_IMAGE" ]; then
    if [ -z "$GRAALVM_HOME" ]; then
        echo "Please set GRAALVM_HOME"
        exit 1
    fi

    "$GRAALVM_HOME/bin/gu" install native-image

    NATIVE_IMAGE="$GRAALVM_HOME/bin/native-image"
fi

CLJ_FMT_VERSION=$(cat resources/cljfmt_graal_version)
JAR_NAME="cljfmt-graalvm"
STANDALONE_NAME=cljfmt

lein "do" clean, uberjar

$NATIVE_IMAGE \
    "-jar" "target/uberjar/${JAR_NAME}-${CLJ_FMT_VERSION}-standalone.jar" \
    "-H:Name=${STANDALONE_NAME}" \
    "-H:+ReportExceptionStackTraces" \
    "-J-Dclojure.spec.skip-macros=true" \
    "-J-Dclojure.compiler.direct-linking=true" \
    "-H:ReflectionConfigurationFiles=reflection.json" \
    "--initialize-at-build-time"  \
    "-H:Log=registerResource:" \
    "--verbose" \
    "--no-fallback" \
    "--no-server" \
    "-J-Xmx3g"
